version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-imap-app
    ports:
      - "8080:80"
    volumes:
      # 앱 소스(개발 편의)
      - ./:/var/www/html
      # 데이터/SQLite 저장소
      - ./data:/var/www/data
      # OpenAI/Gmail 비밀을 담은 config.php를 로컬에서 관리
      - ./config.php:/var/www/html/config.php
    environment:
      # 필요 시 PHP 설정을 ENV로 덮어쓰는 방법(예: imagick 등)
      # - APP_ENV=prod
    restart: unless-stopped
